name: SMSPSA
channels:
  - https://conda.anaconda.org/gurobi
  - defaults
  - conda-forge
dependencies:
  - pluggy=1.0.0
  - sphinx=5.0.2
  - pandas=1.4.4
  - pytest=7.1.2
  - numpy=1.23.1
  - spyder
  - python=3.10.4
  - matplotlib=3.5.2
  - mypy=0.910
  - networkx=3.1
  - pydata-sphinx-theme=0.15.3
  - conda-forge::sphinx-design=0.6.0
